### ISSUE TITLE
Build  Failed  for  Hail Aus model on1.7.1

### ISSUE THREAD

**Issue by nitheeshunni** [risk-frontiers/OasisIntegration#12]
I am getting the below  error  while deploying the  hail 1.7.1
API :1.9.0
UI : 1.8.0
  ERROR: Command errored out with exit status 1:
171      command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/var/oasis/setup.py'"'"'; __file__='"'"'/var/oasis/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-p4sms6wj
172          cwd: /var/oasis/
173     Complete output (9 lines):
174     Traceback (most recent call last):
175       File "<string>", line 1, in <module>
176       File "/var/oasis/setup.py", line 2, in <module>
177         import complex_model
178       File "/var/oasis/complex_model/__init__.py", line 7, in <module>
179         from .HailAUSKeysLookup import *
180       File "/var/oasis/complex_model/HailAUSKeysLookup.py", line 14, in <module>
181         from complex_model.PostcodeDictionary import POSTCODE_CONCORDANCE, POSTCODE_SET, DELIVERY_POSTCODE_SET
182     ModuleNotFoundError: No module named 'complex_model.PostcodeDictionary'
183     ----------------------------------------
184 ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by nitheeshunni** [comment]
issue solved , file was  missing
